//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseImpl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.CandidateCertifications = new HashSet<CandidateCertification>();
            this.CandidateEducations = new HashSet<CandidateEducation>();
            this.CandidateExperiences = new HashSet<CandidateExperience>();
            this.CandidateResumes = new HashSet<CandidateResume>();
            this.CandidateSkills = new HashSet<CandidateSkill>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int AddrId { get; set; }
        public int ContactId { get; set; }
        public Nullable<bool> Authorized { get; set; }
        public Nullable<bool> Relocation { get; set; }
        public string EmploymentType { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<System.DateTime> ReaddyToWorkDate { get; set; }
        public string Notice { get; set; }
        public string Note { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Contact Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateCertification> CandidateCertifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateEducation> CandidateEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateExperience> CandidateExperiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateResume> CandidateResumes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateSkill> CandidateSkills { get; set; }
    }
}
