//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseImpl
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateSkill
    {
        public int Id { get; set; }
        public int CandidateId { get; set; }
        public string SkillName { get; set; }
        public Nullable<int> YearsOfExperience { get; set; }
        public Nullable<int> LastYearUsed { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
